DROP SEQUENCE SEQ_MCODE;
DROP SEQUENCE SEQ_NTC;
DROP SEQUENCE SEQ_INQ;
DROP SEQUENCE SEQ_REV;
DROP SEQUENCE SEQ_GD;

CREATE SEQUENCE SEQ_MCODE
START WITH 10001
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_NTC
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_INQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_REV
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_GD
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

DROP TABLE "TB_MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "TB_USER" CASCADE CONSTRAINTS;
DROP TABLE "TB_RENTAL_SHOP" CASCADE CONSTRAINTS;
DROP TABLE "TB_ADMIN_NOTICE";
DROP TABLE "TB_RESERVATION";
DROP TABLE "TB_PAYMENT";
DROP TABLE "TB_INQUIRY";
DROP TABLE "TB_REVIEW" CASCADE CONSTRAINTS;
DROP TABLE "TB_COUPON";
DROP TABLE "TB_GUIDE";
DROP TABLE "TB_ORDER";
DROP TABLE "TB_COMMENT";
DROP TABLE "TB_ORDER_DETAIL";
DROP TABLE "TB_PIECE_STOCK";
DROP TABLE "TB_SET_PD" CASCADE CONSTRAINTS;
DROP TABLE "TB_REPORT";
DROP TABLE "TB_WISH";

CREATE TABLE TB_MEMBER (
	MEM_CODE NUMBER NOT NULL,
	MEM_ID VARCHAR2(30) NOT NULL,
	MEM_PWD VARCHAR2(20) NOT NULL,
	MEM_NAME VARCHAR2(10) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
	PHONE_VALIDATE CHAR(2) DEFAULT 'N' NOT NULL,
	ENROLL_DATE	DATE DEFAULT SYSDATE NOT NULL,
	MEM_AUTHO VARCHAR2(10) NOT NULL,
	REPORTED_COUNT NUMBER DEFAULT 0	NOT NULL,
	EXPIRED_INFO DATE NOT NULL,
	BLACK_MEM CHAR(2) DEFAULT 'N' NOT NULL,
    STATUS CHAR(2) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_MEM_CODE PRIMARY KEY(MEM_CODE)
);

CREATE TABLE "TB_USER" (
	"MEM_CODE"	NUMBER		NOT NULL,
	"GENDER"	CHAR(2)		NOT NULL,
	"REG_NO"	NUMBER		NULL,
    CONSTRAINT PK_USER_CODE PRIMARY KEY(MEM_CODE),
    CONSTRAINT FK_MEM_CODE FOREIGN KEY(MEM_CODE) REFERENCES TB_MEMBER (MEM_CODE)
);

CREATE TABLE "TB_RENTAL_SHOP" (
	"SHOP_NO"	NUMBER		NOT NULL,
	"SHOP_NAME"	VARCHAR2(50)		NOT NULL,
	"SHOP_PHONE"	NUMBER		NOT NULL,
	"SHOP_BRN"	VARCHAR2(20)		NOT NULL,
	"SHOP_VALIDATE"	VARCHAR2(10)	DEFAULT 'N'	NOT NULL,
	"SHOP_ADDR"	VARCHAR2(100)		NOT NULL,
	"DEPOSIT"	NUMBER		NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "TB_ADMIN_NOTICE" (
	"NOTICE_NO" NUMBER NOT NULL,
	"NOTICE_TITLE" VARCHAR2(50)NOT NULL,
	"NOTICE_CONTENT" VARCHAR2(500)NOT NULL,
	"NOTICE_DATE" DATE DEFAULT SYSDATE NOT NULL,
	"NOTICE_LAST_MD" DATE DEFAULT SYSDATE NOT NULL,
	"NOTICE_COUNT" NUMBER DEFAULT 0 NOT NULL,
	"NOTICE_IMAGE" VARCHAR(255) NULL
);

CREATE TABLE "TB_RESERVATION" (
	"RESERVED_NO"	NUMBER		NOT NULL,
	"RESERVED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RETURN_DATE"	DATE		NULL,
	"REAL_RETURN_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RECEIVED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"RECEIVED_STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"PP_AMOUNT"	NUMBER		NOT NULL,
	"LATE_FEE"	NUMBER		NULL,
	"REFUND_DATE"	DATE		NULL,
	"REFUND_YN"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL,
	"PAY_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TB_PAYMENT" (
	"PAY_NO"	NUMBER		NOT NULL,
	"PAY_AMOUNT"	NUMBER		NOT NULL,
	"PAY_DATE"	DATE		NOT NULL,
	"PAY_STATUS"	CHAR(2)		NOT NULL,
	"ORDER_NO"	NUMBER		NOT NULL,
	"DETAIL_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TB_INQUIRY" (
	"INQ_NO"	NUMBER	NOT NULL,
	"INQ_TITLE"	VARCHAR2(50)		NOT NULL,
	"INQ_CONTENT"	VARCHAR2(500)		NOT NULL,
	"INQ_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INQ_LAST_MD"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INQ_IMAGE"	VARCHAR(255)		NULL,
	"INQ_DEL_STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"ANSWER_CONTENT"	VARCHAR2(500)		NULL,
	"ANSWER_YN"	CHAR(2)	DEFAULT 'N'	NULL,
	"ANSWER_DATE"	DATE		NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "TB_REVIEW" (
	"REVIEW_NO"	NUMBER NOT NULL,
	"REVIEW_TITLE"	VARCHAR2(50)		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(500)		NOT NULL,
	"REVIEW_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_LAST_MD"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REVIEW_DEL_STATUS"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"LIKE_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "TB_GUIDE" (
	"GUIDE_NO"	NUMBER NOT NULL,
	"GUIDE_TITLE"	VARCHAR2(50)		NOT NULL,
	"GUIDE_CONTENT"	VARCHAR2(500)		NOT NULL,
	"GUIDE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"GUIDE_LAST_MD"	DATE	DEFAULT SYSDATE	NOT NULL,
	"GUIDE_COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

CREATE TABLE "TB_COUPON" (
	"COUPON_CODE"	NUMBER		NOT NULL,
	"COUPON_CLASS"	VARCHAR2(20)		NOT NULL,
	"COUPON_VAL"	NUMBER		NOT NULL,
	"COUPON_EXP"	DATE		NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "TB_ORDER" (
	"ORDER_NO"	NUMBER		NOT NULL,
	"DETAIL_NO"	NUMBER		NOT NULL,
	"ORDER_DATE"	DATE		NOT NULL,
	"ORDER_STATUS"	CHAR(2)		NOT NULL,
	"ORDER_TOTAL"	NUMBER		NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);

CREATE TABLE "TB_ORDER_DETAIL" (
	"DETAIL_NO"	NUMBER		NOT NULL,
	"PP_AMOUNT"	NUMBER		NOT NULL,
	"PAY_AMOUNT"	NUMBER		NOT NULL,
	"SP_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TB_PIECE_STOCK" (
	"PP_NO"	NUMBER		NOT NULL,
	"PP_SIZE"	VARCHAR2(10)		NOT NULL,
	"PP_STOCK"	NUMBER		NOT NULL,
	"PP_CATEGORY"	NUMBER		NOT NULL,
	"SP_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TB_COMMENT" (
	"COM_NO" NUMBER NOT NULL,
	"COM_CONTENT" VARCHAR2(300) NOT NULL,
	"COM_DATE" DATE	DEFAULT SYSDATE	NOT NULL,
	"COM_LEVEL" NUMBER NOT NULL,
	"MEM_CODE" NUMBER NOT NULL,
	"REVIEW_NO" NUMBER NOT NULL,
	"COM_NO2" NUMBER NULL
);

CREATE TABLE "TB_SET_PD" (
	"SP_NO"	NUMBER		NOT NULL,
	"SP_NAME"	VARCHAR2(20)		NOT NULL,
	"SP_IMAGE"	VARCHAR(255)		NOT NULL,
	"SP_DETAIL"	VARCHAR2(300)		NOT NULL,
	"SP_COLOR"	VARCHAR2(20)		NOT NULL,
	"SP_GENDER"	VARCHAR2(3)		NOT NULL,
	"SP_PRICE"	NUMBER		NULL,
	"SHOP_NO"	NUMBER		NOT NULL
);

CREATE TABLE "TB_REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_CONTENT"	VARCHAR2(300)		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL,
	"MEM_CODE2"	NUMBER		NOT NULL
);

CREATE TABLE "TB_WISH" (
	"SP_NO"	NUMBER		NOT NULL,
	"MEM_CODE"	NUMBER		NOT NULL
);


ALTER TABLE "TB_RENTAL_SHOP" ADD CONSTRAINT "PK_TB_RENTAL_SHOP" PRIMARY KEY (
	"SHOP_NO"
);

ALTER TABLE "TB_ADMIN_NOTICE" ADD CONSTRAINT "PK_TB_ADMIN_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "PK_TB_RESERVATION" PRIMARY KEY (
	"RESERVED_NO"
);

ALTER TABLE "TB_PAYMENT" ADD CONSTRAINT "PK_TB_PAYMENT" PRIMARY KEY (
	"PAY_NO"
);

ALTER TABLE "TB_INQUIRY" ADD CONSTRAINT "PK_TB_INQUIRY" PRIMARY KEY (
	"INQ_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "PK_TB_REVIEW" PRIMARY KEY (
	"REVIEW_NO"
);

ALTER TABLE "TB_GUIDE" ADD CONSTRAINT "PK_TB_GUIDE" PRIMARY KEY (
	"GUIDE_NO"
);

ALTER TABLE "TB_COUPON" ADD CONSTRAINT "PK_TB_COUPON" PRIMARY KEY (
	"COUPON_CODE"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "PK_TB_ORDER" PRIMARY KEY (
	"ORDER_NO",
	"DETAIL_NO"
);

ALTER TABLE "TB_ORDER_DETAIL" ADD CONSTRAINT "PK_TB_ORDER_DETAIL" PRIMARY KEY (
	"DETAIL_NO"
);

ALTER TABLE "TB_PIECE_STOCK" ADD CONSTRAINT "PK_TB_PIECE_STOCK" PRIMARY KEY (
	"PP_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "PK_TB_COMMENT" PRIMARY KEY (
	"COM_NO"
);

ALTER TABLE "TB_SET_PD" ADD CONSTRAINT "PK_TB_SET_PD" PRIMARY KEY (
	"SP_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "PK_TB_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "TB_WISH" ADD CONSTRAINT "PK_TB_WISH" PRIMARY KEY (
	"SP_NO",
	"MEM_CODE"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "FK_TB_USER_TO_TB_RESERVATION_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_USER" (
	"MEM_CODE"
);

ALTER TABLE "TB_RESERVATION" ADD CONSTRAINT "FK_PAY_NO_TO_RESERVE" FOREIGN KEY (
	"PAY_NO"
)
REFERENCES "TB_PAYMENT" (
	"PAY_NO"
);

ALTER TABLE "TB_PAYMENT" ADD CONSTRAINT "FK_ORDER_NO_TO_PAY" FOREIGN KEY (
	"ORDER_NO",
	"DETAIL_NO"
)
REFERENCES "TB_ORDER" (
	"ORDER_NO",
	"DETAIL_NO"
);

ALTER TABLE "TB_INQUIRY" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_INQUIRY_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_USER_TO_TB_REVIEW_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_USER" (
	"MEM_CODE"
);

ALTER TABLE "TB_COUPON" ADD CONSTRAINT "FK_TB_USER_TO_TB_COUPON_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_USER" (
	"MEM_CODE"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "FK_DETAIL_NO_TO_ORDER" FOREIGN KEY (
	"DETAIL_NO"
)
REFERENCES "TB_ORDER_DETAIL" (
	"DETAIL_NO"
);

ALTER TABLE "TB_ORDER" ADD CONSTRAINT "FK_TB_USER_TO_TB_ORDER_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_USER" (
	"MEM_CODE"
);

ALTER TABLE "TB_ORDER_DETAIL" ADD CONSTRAINT "FK_SP_NO_ORDER_DETAIL" FOREIGN KEY (
	"SP_NO"
)
REFERENCES "TB_SET_PD" (
	"SP_NO"
);

ALTER TABLE "TB_PIECE_STOCK" ADD CONSTRAINT "FK_SP_NO_TO_PP" FOREIGN KEY (
	"SP_NO"
)
REFERENCES "TB_SET_PD" (
	"SP_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_COMMENT_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_REVIEW_TO_TB_COMMENT_1" FOREIGN KEY (
	"REVIEW_NO"
)
REFERENCES "TB_REVIEW" (
	"REVIEW_NO"
);

ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_COM_TO_COM" FOREIGN KEY (
	"COM_NO2"
)
REFERENCES "TB_COMMENT" (
	"COM_NO"
);

ALTER TABLE "TB_SET_PD" ADD CONSTRAINT "FK_SHOP_NO_SET_PD" FOREIGN KEY (
	"SHOP_NO"
)
REFERENCES "TB_RENTAL_SHOP" (
	"SHOP_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPORT_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REPORT_2" FOREIGN KEY (
	"MEM_CODE2"
)
REFERENCES "TB_MEMBER" (
	"MEM_CODE"
);

ALTER TABLE "TB_WISH" ADD CONSTRAINT "FK_TB_SET_PD_TO_TB_WISH_1" FOREIGN KEY (
	"SP_NO"
)
REFERENCES "TB_SET_PD" (
	"SP_NO"
);

ALTER TABLE "TB_WISH" ADD CONSTRAINT "FK_TB_USER_TO_TB_WISH_1" FOREIGN KEY (
	"MEM_CODE"
)
REFERENCES "TB_USER" (
	"MEM_CODE"
);

INSERT INTO TB_MEMBER VALUES(SEQ_MCODE.NEXTVAL, 'admin@odi.com', 'admin', '관리자',
                             '01012341234', DEFAULT, DEFAULT, 'ADMIN', DEFAULT,
                             SYSDATE+365, DEFAULT, DEFAULT);
INSERT INTO TB_MEMBER VALUES(SEQ_MCODE.NEXTVAL, 'user01@odi.com', 'user01', '홍길동',
                             '01012341234', DEFAULT, DEFAULT, 'USER', DEFAULT,
                             SYSDATE+365, DEFAULT, DEFAULT);
INSERT INTO TB_MEMBER VALUES(SEQ_MCODE.NEXTVAL, 'owner01@odi.com', 'owner01', '강보람',
                             '01012341234', DEFAULT, DEFAULT, 'OWNER', DEFAULT,
                             SYSDATE+365, DEFAULT, DEFAULT);

COMMIT;