/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-24 19:02:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/order/../common/header.jsp", Long.valueOf(1569268515873L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>예약 페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("        @font-face { \r\n");
      out.write("                   font-family: 'ON-IGothic'; \r\n");
      out.write("                   src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_eleven@1.0/ON-IGothic.woff') format('woff'); \r\n");
      out.write("                   font-weight: normal; \r\n");
      out.write("                   font-style: normal; \r\n");
      out.write("               }\r\n");
      out.write("                \r\n");
      out.write("                *{\r\n");
      out.write("                    font-family: 'ON-IGothic';\r\n");
      out.write("        \r\n");
      out.write("                }\r\n");
      out.write("    \r\n");
      out.write("        </style>\r\n");
      out.write("        <!-- font-size 15로 통일-->\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("    \t");
      out.write('\r');
      out.write('\n');

	String message = (String)session.getAttribute("msg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/odi-theme.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- common/HEADER -->\r\n");
      out.write("    <header>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header-top-nav\">\r\n");
      out.write("            <ul class=\"header-top-right\">\r\n");
      out.write("                <li>고객센터</li>\r\n");
      out.write("                <li>로그인</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"header-main\">\r\n");
      out.write("            <div class=\"header-logo\">\r\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/logo.png\" alt=\"\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("'\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <ul class=\"nav-bar\">\r\n");
      out.write("                <li>정장대여</li>\r\n");
      out.write("                <li>커뮤니티</li>\r\n");
      out.write("                <li>마이페이지</li>\r\n");
      out.write("                <li>매장찾기</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"line-notice-wrap\">\r\n");
      out.write("            <a href=\"#\">[공지] 추석 연휴 기간 사이트 점검</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        var flag = 0;\r\n");
      out.write("\r\n");
      out.write("        $(window).scroll(function(){\r\n");
      out.write("            if ($(this).scrollTop() >= 150 && flag == 0) {\r\n");
      out.write("                flag = 1;\r\n");
      out.write("                $(\"header\").stop().animate({'height':'86.8px'},{queue:false, duration:300});\r\n");
      out.write("                $(\".header-top-nav\").stop().animate({'height':'0px'},{queue:false, duration:300});\r\n");
      out.write("                $(\".line-notice-wrap\").stop().animate({'height':'0px','display':'none'},{queue:false, duration:300});\r\n");
      out.write("            } else if ($(this).scrollTop() < 150 && flag == 1) {\r\n");
      out.write("                flag = 0;\r\n");
      out.write("                $(\"header\").stop().animate({'height':'140px'},{queue:false, duration:300});\r\n");
      out.write("                $(\".header-top-nav\").stop().animate({'height':'20%'},{queue:false, duration:300});\r\n");
      out.write("                $(\".line-notice-wrap\").stop().animate({'height':'18%'},{queue:false, duration:300});\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("       \t<div style=\"height: 140px;\"></div>\r\n");
      out.write("    \t\r\n");
      out.write("        <div class=\"orderArea\">\r\n");
      out.write("            <h1 align=\"center\"><strong>ORDER SHEET</strong></h1>\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h3>예약 정보</h3>\r\n");
      out.write("                <p class=\"required\">필수입력사항</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"orderInfo\">\r\n");
      out.write("                <h3>상품 주문내역</h3>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"col\"><input type=\"checkbox\" name=\"Infohead\"></th>\r\n");
      out.write("                        <th scope=\"col\">이미지</th>\r\n");
      out.write("                        <th scope=\"col\">상품정보</th>\r\n");
      out.write("                        <th scope=\"col\">판매가</th>\r\n");
      out.write("                        <th scope=\"col\">수량</th>\r\n");
      out.write("                        <th scope=\"col\">대여기간</th>\r\n");
      out.write("                        <th scope=\"col\">합계</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th scope=\"col\"><input type=\"checkbox\" name=\"Infofooter\" id=\"Infofooter\"></th>\r\n");
      out.write("                        <th scope=\"col\">이미지</th>\r\n");
      out.write("                        <th scope=\"col\">정보</th>\r\n");
      out.write("                        <th scope=\"col\">판매가</th>\r\n");
      out.write("                        <th scope=\"col\">수량</th>\r\n");
      out.write("                        <th scope=\"col\" colspan=\"2\">대여기간별 가격추가</th>\r\n");
      out.write("                        <th scope=\"col\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"Total_sum\">\r\n");
      out.write("                    <input type=\"text\" name=\"total_price\" id=\"total_price\" placeholder=\"예약정보 가격 = 합계\" size=\"30\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"typeWrite\">\r\n");
      out.write("                <table border=\"0\" summary=\"\">\r\n");
      out.write("                    <caption>정보 입력</caption>\r\n");
      out.write("    \r\n");
      out.write("                    <tbody></tbody>\r\n");
      out.write("    \r\n");
      out.write("                    <tbody class=\"\">\r\n");
      out.write("                        <tr class=\"\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"row\">예약 성명*</th>\r\n");
      out.write("                            <td><input id=\"rname\" name=\"rname\" class=\"inputTypeText\" placeholder=\"\" size=\"15\" value=\"\" type=\"text\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"row\">성별*</th>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"gender_m\" id=\"gender_m\"> 남자\r\n");
      out.write("                                <input type=\"radio\" name=\"gender_w\" id=\"gender_w\"> 여자\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"row\">주소*</th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input id=\"raddr1\" name=\"raddr1\" class=\"inputTypeText\" placeholder=\"\" size=\"40\" readonly=\"1\"\r\n");
      out.write("                                    value=\"\" type=\"text\"> <span class=\"grid\">기본주소</span><br>\r\n");
      out.write("                                <input id=\"raddr2\" name=\"raddr2\" class=\"inputTypeText\" placeholder=\"\" size=\"40\" value=\"\"\r\n");
      out.write("                                    type=\"text\">\r\n");
      out.write("                                <span class=\"grid\">나머지주소</span><span class=\"grid \">(선택입력가능)</span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"\">\r\n");
      out.write("                            <th scope=\"row\">휴대전화* <span class=\"\"></span>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <td><select id=\"rphone2_1\" name=\"rphone2_[]\">\r\n");
      out.write("                                    <option value=\"010\">010</option>\r\n");
      out.write("                                    <option value=\"011\">011</option>\r\n");
      out.write("                                    <option value=\"016\">016</option>\r\n");
      out.write("                                    <option value=\"017\">017</option>\r\n");
      out.write("                                    <option value=\"018\">018</option>\r\n");
      out.write("                                    <option value=\"019\">019</option>\r\n");
      out.write("                                </select>-<input id=\"rphone2_2\" name=\"rphone2_[]\" maxlength=\"4\" size=\"4\" value=\"\" type=\"text\">-<input\r\n");
      out.write("                                    id=\"rphone2_3\" name=\"rphone2_[]\" maxlength=\"4\" size=\"4\" value=\"\" type=\"text\">\r\n");
      out.write("                                &nbsp;&nbsp;<input type=\"button\" name=\"Authentication\" id=\"Authentication\" value=\"인증\">\r\n");
      out.write("                            </td>\r\n");
      out.write("    \r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr class=\"displaynone\">\r\n");
      out.write("                    </tbody>\r\n");
      out.write("    \r\n");
      out.write("                    <tbody class=\"email \">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"row\">이메일</th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input id=\"oemail1\" name=\"oemail1\" class=\"mailId\" value=\"\" type=\"text\">@<input id=\"oemail2\"\r\n");
      out.write("                                    name=\"oemail2\" class=\"mailAddress\" value=\"\" type=\"text\"><select id=\"oemail3\">\r\n");
      out.write("                                    <option value=\"\" selected=\"selected\">- 이메일 선택 -</option>\r\n");
      out.write("                                    <option value=\"naver.com\">naver.com</option>\r\n");
      out.write("                                    <option value=\"daum.net\">daum.net</option>\r\n");
      out.write("                                    <option value=\"nate.com\">nate.com</option>\r\n");
      out.write("                                    <option value=\"hotmail.com\">hotmail.com</option>\r\n");
      out.write("                                    <option value=\"yahoo.com\">yahoo.com</option>\r\n");
      out.write("                                    <option value=\"empas.com\">empas.com</option>\r\n");
      out.write("                                    <option value=\"korea.com\">korea.com</option>\r\n");
      out.write("                                    <option value=\"dreamwiz.com\">dreamwiz.com</option>\r\n");
      out.write("                                    <option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("                                    <option value=\"etc\">직접입력</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr></tbody>\r\n");
      out.write("                        \r\n");
      out.write("                        <tbody class=\"requestmsg displaynone\">\r\n");
      out.write("                            <tr class=\"\">\r\n");
      out.write("                                <th scope=\"row\">요청메시지 <span class=\"displaynone\"></span>\r\n");
      out.write("                                </th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <div class=\"automsg displaynone\">\r\n");
      out.write("                                        <div class=\"re_text\">\r\n");
      out.write("                                            <textarea name=\"requestmsg\" id=\"requestmsg\" cols=\"55\" rows=\"5\"></textarea><br>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <label> 자동저장</label>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li>요청메시지란에는 예약시 참고할 사항이 있으면 적어주십시오.</li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <div></div>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"shop_policy\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td><input type=\"checkbox\" name=\"checkbox\" id=\"checkbox\"></td>\r\n");
      out.write("                                <td>쇼핑몰 이용약관</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"text_policy\">\r\n");
      out.write("                            <textarea name=\"text_policy\" id=\"text_policy\" cols=\"55\" rows=\"5\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <div class=\"order_history\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            <td>&gt;&gt; 예약내역 조회/변경/취소/연장</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <div class=\"Or_history_text\">\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <textarea name=\"history_txt\" id=\"history_txt\" cols=\"55\" rows=\"5\"></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"title\">\r\n");
      out.write("                        <h3>결제예정 금액정보</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"totalArea\">\r\n");
      out.write("                        <div class=\"totalArea\">\r\n");
      out.write("                            <div class=\"total TypeList\">\r\n");
      out.write("                                <table class=\"order_total_tb\" border=\"1\" summary=\"\">\r\n");
      out.write("                                    <caption>결제 예정 금액</caption>\r\n");
      out.write("                                    <colgroup>\r\n");
      out.write("                                        <col style=\"width:33.33%\">\r\n");
      out.write("                                        <col style=\"width:33.33%\" class=\"\">\r\n");
      out.write("                                        <col style=\"width:33.33%\">\r\n");
      out.write("                                    </colgroup>\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th scope=\"col\">\r\n");
      out.write("                                                <strong>총 주문 금액</strong> &nbsp; &nbsp;\r\n");
      out.write("                                            </th>\r\n");
      out.write("                                            <th scope=\"col\" class=\"\">\r\n");
      out.write("                                                <strong>총 </strong><strong id=\"total_addsale_text\" class=\"\">할인</strong><strong\r\n");
      out.write("                                                    id=\"plus_mark\" class=\"\"> + </strong><strong id=\"total_addpay_text\"\r\n");
      out.write("                                                    class=\"\">부가결제</strong><strong>\r\n");
      out.write("                                                    금액</strong>\r\n");
      out.write("                                            </th>\r\n");
      out.write("                                            <th scope=\"col\"><strong>총 결제예정 금액</strong></th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody class=\"center\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td class=\"price\">\r\n");
      out.write("                                                <div class=\"box txt16\">\r\n");
      out.write("                                                    <strong><span id=\"total_order_price_view\" class=\"txt21\">99,000</span>\r\n");
      out.write("                                                        won</strong>\r\n");
      out.write("                                                    <span class=\"displaynone\"><span id=\"total_order_price_ref_view\"></span></span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td class=\"option \">\r\n");
      out.write("                                                <div class=\"box txt16\">\r\n");
      out.write("                                                    <strong>-</strong> <strong><span id=\"total_sale_price_view\" class=\"txt21\">0</span>\r\n");
      out.write("                                                        won</strong> <span class=\"displaynone\"><span id=\"total_sale_price_ref_view\"></span></span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <div class=\"box txtEm txt16\">\r\n");
      out.write("                                                    <strong><span id=\"total_order_sale_price_view\" class=\"txt21\">99,000</span>\r\n");
      out.write("                                                        won</strong> <span class=\"displaynone\"><span id=\"total_order_sale_price_ref_view\"></span></span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"detail\">\r\n");
      out.write("                                <div class=\"ec-base-table gMerge \">\r\n");
      out.write("                                    <table class=\"order_total_tb\" border=\"1\" summary=\"\">\r\n");
      out.write("                                        <caption>할인 내역</caption>\r\n");
      out.write("                                        <colgroup>\r\n");
      out.write("                                            <col style=\"width:139px\">\r\n");
      out.write("                                            <col style=\"width:auto\">\r\n");
      out.write("                                        </colgroup>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr class=\"sum txt14\">\r\n");
      out.write("                                                <th scope=\"row\"><strong>총 할인금액</strong></th>\r\n");
      out.write("                                                <td><strong id=\"total_addsale_price_view\">0</strong> won</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr class=\"displaynone mCouponSelect\" style=\"display: table-row;\">\r\n");
      out.write("                                                <th scope=\"row\">쿠폰할인</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr class=\"mCouponModify\" style=\"display: none;\">\r\n");
      out.write("                                                <th scope=\"row\">쿠폰할인</th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <span class=\"mTotalCouponDiscount\">0 won</span>\r\n");
      out.write("                                                    <div id=\"divCpnView\" style=\"display:none\" class=\"coupon\">\r\n");
      out.write("                                                        <span id=\"txt_cpn_contents\"></span>\r\n");
      out.write("                                                        <span id=\"txt_cpn_price\"></span>\r\n");
      out.write("                                                        <span id=\"txt_cpn_attr_D\"></span>\r\n");
      out.write("                                                        <span id=\"txt_cpn_attr_M\"></span>\r\n");
      out.write("                                                        <span id=\"txt_cpn_attr_C\"></span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div id=\"divCpn\" style=\"display:none\" class=\"couponArea\"></div>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr class=\"displaynone\" id=\"add_discount_price\">\r\n");
      out.write("                                                <th scope=\"row\">추가할인금액</th>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <span class=\"gSpace20\"><span id=\"total_price_view\">0</span> won</span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"info_title\">\r\n");
      out.write("                                <h3>결제 수단</h3>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"payment_method\">\r\n");
      out.write("                                    <table>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"checkbox\" name=\"card_pay\" id=\"card_pay\">\r\n");
      out.write("                                                <label for=\"\">카드 결제</label>\r\n");
      out.write("                                            </td>   \r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"checkbox\" name=\"passbook_pay\" id=\"passbook_pay\">\r\n");
      out.write("                                                <label for=\"\">무통장 결제</label>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"checkbox\" name=\"phone_pay\" id=\"phone_pay\">\r\n");
      out.write("                                                <label for=\"\">휴대폰 결제(소액결제)</label>\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
